name: Deploy Lambda function with Docker container

env:
  ECR_REPOSITORY: {{ cookiecutter.ecr_repository }}
  LAMBDA_ROLE_ARN: {{ cookiecutter.lambda_function_role_arn }}
  LAMBDA_CONTAINER_NAME: {{ cookiecutter.lambda_container_name }}
  # set env from secrets
  AWS_REGION: {% raw %}${{ secrets.AWS_REGION }}{% endraw %}
  AWS_ACCOUNT: {% raw %}${{ secrets.AWS_ACCOUNT }}{% endraw %}

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: {% raw %}${{ secrets.AWS_ACCESS_KEY_ID }}{% endraw %}
        aws-secret-access-key: {% raw %}${{ secrets.AWS_SECRET_ACCESS_KEY }}{% endraw %}
        aws-region: {% raw %}${{ secrets.AWS_REGION }}{% endraw %}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:{% raw %}${{ github.sha }}{% endraw %}
  
    - name: Deploy Lambda function
      run: |
        export IMAGE_TAG={% raw %}${{ github.sha }}{% endraw %}
        export IMAGE_URI=$AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:{% raw %}${{ github.sha }}{% endraw %}
        FUNCTION_ARN=$(aws lambda get-function --function-name $LAMBDA_CONTAINER_NAME --query 'Configuration.FunctionArn' --output text || true)
        
        if [ -z "$FUNCTION_ARN" ]; then
          aws lambda create-function \
              --function-name $LAMBDA_CONTAINER_NAME \
              --role arn:aws:iam::$AWS_ACCOUNT:role/service-role/$LAMBDA_ROLE_ARN \
              --package-type Image --code ImageUri=$IMAGE_URI \
              --timeout 15 \
              --memory-size 256
        else
         aws lambda update-function-code \
              --function-name $LAMBDA_CONTAINER_NAME \
              --image-uri $IMAGE_URI \
              --publish
        
        # wait for the lambda function to complete the update before applying any config
        aws lambda wait function-updated \
          --function-name $LAMBDA_CONTAINER_NAME

         aws lambda update-function-configuration \
           --function-name $LAMBDA_CONTAINER_NAME \
           --timeout 15 \
           --memory-size 256
        fi
