name: Deploy Lambda Function

env:
  LAMBDA_FUNCTION_NAME: {{ cookiecutter.lambda_function_name }}

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Package Lambda function
      run: |
        mkdir package
        cp -r src/* package/
        cd package
        pip install -r ../requirements.txt --target .
        zip -r ../lambda_function.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: {% raw %}${{ secrets.AWS_ACCESS_KEY_ID }}{% endraw %}
        aws-secret-access-key: {% raw %}${{ secrets.AWS_SECRET_ACCESS_KEY }}{% endraw %}
        aws-region: {% raw %}${{ secrets.AWS_REGION }}{% endraw %}

    - name: Deploy Lambda function
      run: |
        aws lambda update-function-code \
             --function-name $LAMBDA_FUNCTION_NAME \
             --zip-file fileb://lambda_function.zip
