name: Deploy Lambda function with Docker container

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: 305611566641.dkr.ecr.us-east-1.amazonaws.com/lambda-container-repo:${{ github.sha }}
  
    - name: Deploy Lambda function
      run: |
        export IMAGE_TAG=${{ github.sha }}
        export IMAGE_URI=305611566641.dkr.ecr.us-east-1.amazonaws.com/lambda-container-repo:${{ github.sha }}
        FUNCTION_ARN=$(aws lambda get-function --function-name lambda-container --query 'Configuration.FunctionArn' --output text || true)
        if [ -z "$FUNCTION_ARN" ]; then
          aws lambda create-function \
              --function-name lambda-container \
              --role arn:aws:iam::305611566641:role/service-role/github-actions-test-role-fj1yq5zk \
              --package-type Image --code ImageUri=$IMAGE_URI \
              --timeout 15 \
              --memory-size 256
        else
         aws lambda update-function-code \
              --function-name lambda-container \
              --image-uri $IMAGE_URI
         aws lambda update-function-configuration \
           --function-name lambda-container \
           --timeout 15 \
           --memory-size 256
        fi
