name: Deploy Custom Layer

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Package custom layer
      run: |
        mkdir package
        cp -r layers/* package
        cd package
        pip install -r ../layer_requirements.txt --target .
        zip -r ../custom_layer.zip .

    - name: Upload custom layer to S3
      run: |
        aws s3 cp custom_layer.zip s3://lambda-layer-zips-fn/pandas_lambda_layer.zip

    - name: Publish custom layer
      run: |
        aws lambda publish-layer-version --layer-name PANDAS_LAYER --content S3Bucket=lambda-layer-zips-fn,S3Key=pandas_lambda_layer.zip
